### ISSUE TITLE
Does it work for you ?

### ISSUE THREAD

**Issue by Rhylx** [mapa0402/renewNoip#1]
Hi,
I wanned to know if this is working for you, because I tried to use your script,
everything seemed to work well (good console.log) but nothing really changed on noip.com (meaning confirm button wasn't pushed).
I'm struggling to find a script that is working for me.
I'm ready to help you to make this work out if you need some help.
Best,
Rhylx

**Comment by mapa0402** [comment]
Hi, sorry for the bad info and documentation I'm working on it atm.

Yes the script is working for me, but the confirm button is only available and active when it's 7 or less days remaining to renew the domain.

**Comment by Rhylx** [comment]
Yep, yesterday it was the last day and I tried it out, but when I logged into noip.com, the butoon wasn't pushed, that's weird...
Anyway, I'll try it again at the end of this month

**Comment by Rhylx** [comment]
I have tested it again and it doesn't work even if I have the success message that you console.log. I don't really know why it doesn't work, my guess is that the script isn't hitting the right button. Have you tested it again ?

**Comment by mapa0402** [comment]
Hi, it didn't work now so I will investigate, probably something has
changed in their GUI. thanks for reporting!

**Comment by mapa0402** [comment]
It did work now, I added a try/catch when running code and updated the cronjob time.
`var job = new CronJob('01 01 0 * * *'`
means it will run **0th** hour **01th** minute and **01th** second, ie **once** a day. If I run it like every minute or second it did crash.

**Comment by Rhylx** [comment]
Ok, so does it work now?
My feeling is that it's not catching the button correctly

**Comment by mapa0402** [comment]
The button will only be visible when you start get the "remember to renew" emails, but the script will not try to click if it's 7 days or more to renew.
