### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [mapa0402/renewNoip#2]

**Comment by mapa0402** [comment]
the script renews if its 7 days or less.
Run it as a docker container or schedule the script to use automatically

**Comment by bphd** [comment]
For real? Captcha and all?

**Comment by mapa0402** [comment]
no captcha, this script takes advance of the "remember to renew" emails you get when its 7 days or less, a login and renew button that doesn't require captcha.
